"""init tables

Revision ID: 59085e4c2fa3
Revises: 
Create Date: 2026-01-10 17:23:32.307210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59085e4c2fa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_cache',
    sa.Column('place_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address_name', sa.String(length=300), nullable=False),
    sa.Column('road_address_name', sa.String(length=300), nullable=False),
    sa.Column('place_url', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('category_name', sa.String(length=300), nullable=False),
    sa.Column('category_group_code', sa.String(length=10), nullable=False),
    sa.Column('category_group_name', sa.String(length=50), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('zones',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('crowding_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('updated_at_epoch', sa.BigInteger(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['zone_code'], ['zones.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowding_snapshots_ts'), 'crowding_snapshots', ['ts'], unique=False)
    op.create_index(op.f('ix_crowding_snapshots_zone_code'), 'crowding_snapshots', ['zone_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowding_snapshots_zone_code'), table_name='crowding_snapshots')
    op.drop_index(op.f('ix_crowding_snapshots_ts'), table_name='crowding_snapshots')
    op.drop_table('crowding_snapshots')
    op.drop_table('zones')
    op.drop_table('place_cache')
    # ### end Alembic commands ###
